#!/bin/tcsh -f



set my_work_dir='pwd'
if ($#argv != 1) then
    echo "Info: Please provide the csv file"
    exit 1
endif
if(! -f $argv[1] || $argv[1] == "-help") then
     if ($argv[1] != "help") then
            echo "Error: Cannot find csv file $argv[1]. Existing..."
           exit 1
       else
           echo USAGE: ./vsdsynth\<csv file\>
           echo
           echo        where\<csv file\> consists of 2 columns, below keyboard being in 1st column and is Case Sensitive. Please request VSD team for sample csv file
          echo
          echo        \<Design Name\> is the name of the top level module
           echo
           echo        \<Output Directory\> is the name of output directory where u want to dump synthesis script, synthesisided netlist and timing reports
           echo     
           echo         \<Netlist Directory\> is the name of the directory where all RTL netlist are present
           echo
           echo         \<Early Library path\> is the file path of the early cell library to be used for STA
           echo
           echo         \<Late Library Path\>  is file path of the late cell library to be used for STA
           echo
           echo         \<Constraints file\> is csv file path of the constraints to be used for STA
           echo
          exit 1
    endif
else
         tclsh vsdsynth.tcl $argv[1]
endif

